export const sidebarConfig = {
  documentRootPath: "/docs",
  useTitleFromFileHeading: true,
  useTitleFromFrontmatter: true,
  useFolderTitleFromIndexFile: true,
  // useFolderLinkFromIndexFile: false,
  // hyphenToSpace: true,
  // underscoreToSpace: true,
  // capitalizeFirst: true,
  // capitalizeEachWords: true,
  collapsed: true,
  collapseDepth: 2,
  // sortMenusByName: false,
  // sortMenusByFrontmatterOrder: false,
  // sortMenusByFrontmatterDate: false,
  // sortMenusOrderByDescending: false,
  // sortMenusOrderNumericallyFromTitle: false,
  // sortMenusOrderNumericallyFromLink: false,
  // frontmatterOrderDefaultValue: 0,
  // manualSortFileNameByPriority: ['first.md', 'second', 'third.md'],
  // removePrefixAfterOrdering: false,
  // prefixSeparator: '.',
  excludePattern: ["tags.md"],
  // excludeFilesByFrontmatter: false,
  // includeDotFiles: false,
  // includeRootIndexFile: false,
  // includeFolderIndexFile: false,
  // includeEmptyFolder: false,
  // rootGroupText: 'Contents',
  // rootGroupLink: 'https://github.com/jooy2',
  // rootGroupCollapsed: false,
  // convertSameNameSubFileToGroupIndexPage: false,
  // folderLinkNotIncludesFileName: false,
  // keepMarkdownSyntaxFromTitle: false,
  // debugPrint: true,
};
