/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleInfo: typeof import('./.vitepress/theme/components/ArticleInfo.vue')['default']
    ArticleWaterfallList: typeof import('./.vitepress/theme/components/ArticleWaterfallList.vue')['default']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ElyButton: typeof import('./.vitepress/theme/components/ElysiumUI/ElyButton.vue')['default']
    ElyCard: typeof import('./.vitepress/theme/components/ElysiumUI/ElyCard.vue')['default']
    ElyEmptyState: typeof import('./.vitepress/theme/components/ElysiumUI/ElyEmptyState.vue')['default']
    ElyIconBreve: typeof import('./.vitepress/theme/components/ElysiumUI/ElyIcon/ElyIconBreve.vue')['default']
    ElyIconEmpty: typeof import('./.vitepress/theme/components/ElysiumUI/ElyIcon/ElyIconEmpty.vue')['default']
    ElyImage: typeof import('./.vitepress/theme/components/ElysiumUI/ElyImage.vue')['default']
    ElyImageGallery: typeof import('./.vitepress/theme/components/ElysiumUI/ElyImageGallery.vue')['default']
    ElyImagePreview: typeof import('./.vitepress/theme/components/ElysiumUI/ElyImagePreview.vue')['default']
    ElyPagination: typeof import('./.vitepress/theme/components/ElysiumUI/ElyPagination.vue')['default']
    ElyProfile: typeof import('./.vitepress/theme/components/ElysiumUI/ElyProfile.vue')['default']
    ElySpace: typeof import('./.vitepress/theme/components/ElysiumUI/ElySpace.vue')['default']
    ElyTag: typeof import('./.vitepress/theme/components/ElysiumUI/ElyTag.vue')['default']
    HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
    IconClockCircle: typeof import('@arco-design/web-vue/es/icon')['IconClockCircle']
    IconClose: typeof import('@arco-design/web-vue/es/icon')['IconClose']
    IconDoubleDown: typeof import('@arco-design/web-vue/es/icon')['IconDoubleDown']
    IconEmail: typeof import('@arco-design/web-vue/es/icon')['IconEmail']
    IconHistory: typeof import('@arco-design/web-vue/es/icon')['IconHistory']
    IconLeft: typeof import('@arco-design/web-vue/es/icon')['IconLeft']
    IconRight: typeof import('@arco-design/web-vue/es/icon')['IconRight']
    IconTag: typeof import('@arco-design/web-vue/es/icon')['IconTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagSearchPage: typeof import('./.vitepress/theme/components/TagSearchPage.vue')['default']
  }
}
