/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ASwitch: (typeof import("@arco-design/web-vue"))["Switch"];
    ATag: (typeof import("@arco-design/web-vue"))["Tag"];
    HomePage: (typeof import(".vitepress/theme/HomePage.vue"))["default"];
    ProfileCard: (typeof import(".vitepress/theme/ProfileCard.vue"))["default"];
    ArticleCard: (typeof import(".vitepress/theme/ArticleCard.vue"))["default"];
    TableOfContents: (typeof import(".vitepress/theme/TableOfContents.vue"))["default"];
  }
}
