name: Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: "blog"
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://mark9804.github.io/blog/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: actions/setup-node@main
        with:
          node-version: "20"
      - uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Build
        run: |
          pnpm install
          pnpm run build
      - name: Setup Pages
        uses: actions/configure-pages@main
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: ./docs/.vitepress/dist
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@main